@url = http://localhost:5000
@genreId=57997c5e-e4e1-4d36-9a9e-9ed0553be80a
@directorId=5ea1bfb5-2936-4429-ad74-02c9665cb4ef

###
GET {{url}}/genres
Accept: application/json

###
GET {{url}}/genres/{{genreId}}
Accept: application/json

###
POST {{url}}/genres
Accept: application/json
Content-Type: application/json

{
  "name": "horror"
}

###
PUT {{url}}/genres/{{genreId}}
Accept: application/json
Content-Type: application/json

{
  "name": "thriller"
}

###
DELETE {{url}}/genres/{{genreId}}
Accept: application/json

###
GET {{url}}/directors
Accept: application/json

###
GET {{url}}/directors/{{directorId}}
Accept: application/json

###
POST {{url}}/directors
Accept: application/json
Content-Type: application/json

{
  "firstname": "Andrzej",
  "lastname": "Wajda"
}

###
PUT {{url}}/directors/{{directorId}}
Accept: application/json
Content-Type: application/json

{
  "firstname": "Agnieszka",
  "lastname": "Holland"
}

###
DELETE {{url}}/directors/{{directorId}}
Accept: application/json