@url = http://localhost:5000
@genreId=2f1b03e5-509d-458d-8ab5-ba3025b29f51
@directorId=5a118161-f073-4852-ba67-5026e020626c
@movieId=37e0ce2a-64e4-42a8-b8b9-2763dd6a1bf3
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NzczZTYyYi0zM2RlLTRhMTItYWQzMi0yOWQ4YTQ3MWNkMjQiLCJ1bmlxdWVfbmFtZSI6IjQ3NzNlNjJiLTMzZGUtNGExMi1hZDMyLTI5ZDhhNDcxY2QyNCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImFkbWluIiwibmJmIjoxNzEzNzcwNDEzLCJleHAiOjE3MTM3NzQwMTMsImlzcyI6Im1vdmllcy1yYXRpbmctaXNzdWVyIiwiYXVkIjoibW92aWVzLXJhdGluZy1hdWRpZW5jZSJ9.6Ixw2aneDOTAbp_Jg-g0v0ELhCVtImBqG5For8DGtMI
@userId=29eada5e-324b-4b5b-8ae3-8aad2a158172

###
GET {{url}}/genres?PageSize=3&PageNumber=1
Accept: application/json

###
GET {{url}}/genres/{{genreId}}
Accept: application/json

###
POST {{url}}/genres
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "dramat"
}

###
PUT {{url}}/genres/{{genreId}}
Accept: application/json
Content-Type: application/json

{
  "name": "komedia"
}

###
DELETE {{url}}/genres/{{genreId}}
Accept: application/json

###
GET {{url}}/directors
Accept: application/json

###
GET {{url}}/directors/{{directorId}}
Accept: application/json

###
POST {{url}}/directors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstname": "Andrzej",
  "lastname": "Wajda"
}

###
PUT {{url}}/directors/{{directorId}}
Accept: application/json
Content-Type: application/json

{
  "firstname": "Agnieszka",
  "lastname": "Holand"
}

###
DELETE {{url}}/directors/{{directorId}}
Accept: application/json

###
GET {{url}}/movies
Accept: application/json

###
GET {{url}}/movies/{{movieId}}
Accept: application/json

###
POST {{url}}/movies
Accept: application/json
Content-Type: application/json

{
  "title": "Obecnoœæ",
  "yearofproduction": "2010",
  "description": "A family looks to prevent evil spirits from trapping their comatose child in a realm called The Further.",
  "genreId": "56c49023-b28d-4d1b-adbf-b40b635553bc",
  "directorId": "ec172fae-7eee-458e-bc4b-da6c1ec1f0c2"
}

###
PUT {{url}}/movies/{{movieId}}
Accept: application/json
Content-Type: application/json

{
  "title": "The Conjuring",
  "yearofproduction": "2013",
  "description": "The Conjuring is a 2013 supernatural horror film inspired by the true-life story of the Perron family, who claimed they 'lived among the dead' in the 1970s as spirits both friendly and sinister inhabited their Rhode Island farmhouse.",
  "genreId": "56c49023-b28d-4d1b-adbf-b40b635553bc",
  "directorId": "ec172fae-7eee-458e-bc4b-da6c1ec1f0c2"
}

###
DELETE {{url}}/movies/{{movieId}}
Accept: application/json

###
POST {{url}}/account/sign-up
Accept: application/json
Content-Type: application/json

{
  "userName": "administrator",
  "email": "administrator@email.com",
  "password": "test",
  "fullName": "Administrator Systemu",
  "role": "admin"
}

###
POST {{url}}/account/sign-in
Accept: application/json
Content-Type: application/json

{
  "userName": "administrator",  
  "password": "test"  
}

###
GET {{url}}/account/me
Authorization: Bearer {{token}}

###
PUT {{url}}/account/{{userId}}/change-password
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "test2"
}

###
PUT {{url}}/account/{{userId}}/change-role
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "newRole": "admin"
}

###
PUT {{url}}/account/{{userId}}/edit-user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userName": "billyjoe",
  "email": "billy.joe@gmail.com",
  "fullName": "Billy Joe"
}